version: '2'

services:
    app:
      container_name: m2-app
      image: luckyraul/docker-dummy
      volumes:
        - ./application:/var/www/public
    php:
      container_name: m2-php
      image: mygento/php:7.1-full             
      volumes_from:
       - app
      links:
       - redis
       - db
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_URL=backend
        - APPLICATION_MODE=development
        - PHPFPM_USER=$USERID
    redis:
      image: redis:3
      container_name: m2-redis
    nginx:
      container_name: m2-nginx
      image: luckyraul/nginx:backports
      environment:
        - NGINX_USER=$USERID
      ports:
       - 8081:80
      volumes:
        - ./conf/nginx:/etc/nginx/sites-enabled/
      volumes_from:
       - app
      depends_on:
       - php
    db:
      container_name: m2-db
      image: mygento/mysql
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb_file_per_table
      ports:
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=mygento
       - MYSQL_DATABASE=magento
       - MYSQL_USER=mygento
       - MYSQL_PASSWORD=mygento
      volumes:
       - "m2-db-data:/var/lib/mysql"
volumes:
    m2-db-data:
